name: Build Minecraft Mod
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 for Gradle
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: gradle build -Dorg.gradle.java.home=${{ env.JAVA_HOME_8_X64 }}
        env:
          JAVA_HOME_8_X64: /usr/lib/jvm/temurin-8-jdk-amd64
        # Если возникнет ошибка с путем, мы попробуем другой способ в следующем шаге
